---

- name: Wait until testpmd-app pod is deleted from the drained node
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: "{{ cnf_namespace }}"
    name: "{{ cnf_existing_pod }}"
  register: cnf_pod
  until: cnf_pod.resources|length == 0
  retries: 24
  delay: 5

- name: Get timestamp to save the time when testpmd-app was removed
  ansible.builtin.shell: "date +%s"
  register: timestamp_pod_deletion

- name: Wait until new testpmd-app pod is allocated in a new worker node
  community.kubernetes.k8s_info:
    namespace: "{{ cnf_namespace }}"
    kind: Pod
    label_selectors:
      - example-cnf-type=cnf-app
  register: cnf_pod
  vars:
    container_state_running_query: "resources[0].status.containerStatuses[?name=='testpmd'].state.running"
    container_started_query: "resources[0].status.containerStatuses[?name=='testpmd'].started"
    container_ready_query: "resources[0].status.containerStatuses[?name=='testpmd'].ready"
    container_state_running: "{{ cnf_pod | json_query(container_state_running_query) }}"
    container_started: "{{ cnf_pod | json_query(container_started_query) }}"
    container_ready: "{{ cnf_pod | json_query(container_ready_query) }}"
  retries: 12
  delay: 10
  until:
    - cnf_pod.resources[0].status.phase == 'Running'
    - container_state_running | length > 0
    - container_started | length > 0
    - container_started[0] | bool
    - container_ready | length > 0
    - container_ready[0] | bool

- name: Get timestamp to save the time when testpmd-app was recreated
  ansible.builtin.shell: "date +%s"
  register: timestamp_pod_recreation

- name: Retrieve context information from new testpmd pod
  set_fact:
    cnf_new_node: "{{ cnf_pod.resources[0].spec.nodeName }}"
    cnf_new_pod: "{{ cnf_pod.resources[0].metadata.name }}"

- name: Confirm that a new testpmd-app pod has been created, and in a different worker node
  ansible.builtin.assert:
    that:
      - cnf_new_node != cnf_existing_node
      - cnf_new_node != pktgen_existing_node
      - cnf_new_pod != cnf_existing_pod
    fail_msg: "New testpmd-app pod does not match the conditions defined to consider it is a new one"

- name: Uncordon the node after finishing the draining and rescheduling process
  ansible.builtin.shell: |
    {{ oc_tool_path }} adm uncordon {{ cnf_existing_node }}

...
