---
- name: create cr for loadbalancer
  k8s:
    definition: "{{ lookup('template', 'lb-cr.yaml.j2') }}"

- name: check loadbalancer pod status to be running
  k8s_info:
    namespace: "{{ cnf_namespace }}"
    kind: Pod
    label_selectors:
      - example-cnf-type=lb-app
  register: lb_pods
  vars:
    terminated: "resources[0].status.containerStatuses[?name=='loadbalancer'].state.terminated"
    terminated_containers: "{{ lb_pods | json_query(terminated) }}"
  retries: 60
  delay: 5
  until:
    - lb_pods.resources | length == 1
    - lb_pods.resources[0].status.phase in ['Running', 'Pending']
    - terminated_containers | length == 0
