---
- name: create cr for loadbalancer
  k8s:
    definition: "{{ lookup('template', 'lb-cr.yaml.j2') }}"

- name: Wait for updated MC to be applied on the nodes and retrieve logs
  include_tasks: mcp_wait_and_logs.yml

- name: check loadbalacer pod count to be 1
  k8s_info:
    namespace: "{{ cnf_namespace }}"
    kind: Pod
    label_selectors:
      - example-cnf-type=lb-app
  register: lb_pods
  retries: 60
  delay: 5
  until:
    - lb_pods.resources|length == 1
- name: check loadbalancer pod status to be running
  k8s_info:
    namespace: "{{ cnf_namespace }}"
    kind: Pod
    label_selectors:
      - example-cnf-type=lb-app
  register: lb_pods
  retries: 60
  delay: 5
  until:
    - lb_pods.resources[0].status.phase == 'Running'

