---
# Customizable variables
operator_version: ""
app_version: ""
registry_url: quay.io
repo_name: rh-nfv-int
enable_trex: true
enable_trex_app: true
enable_lb: true

# Internal variables
termination_grace_period_seconds: 30

image_pull_policy: Always
catalog_name: nfv-example-cnf-catalog
# To guarantee support to disconnected environments, this image must be the
# same as the one used by the testpmd-operator and must use its digest.
# https://github.com/rh-nfv-int/testpmd-operator/blob/master/relatedImages.yaml#L3
image_testpmd: "registry.redhat.io/openshift4/dpdk-base-rhel8@sha256:9af03fb4c5ae1c51f71ad04f02fee8e9458aa73c3f4324e984c731d07896c4e1"  # v4.6.3

cnf_namespace: example-cnf

testpmd_channel: alpha
trex_channel: alpha

trex_cr_name: trexconfig

trex_mac_list: ["20:04:0f:f1:89:01","20:04:0f:f1:89:02"]

lb_gen_port_mac_list: ["40:04:0f:f1:89:01","40:04:0f:f1:89:02"]
lb_cnf_port_mac_list: ["60:04:0f:f1:89:01","60:04:0f:f1:89:02"]

cnf_app_networks: []

packet_generator_networks: []

packet_rate: 10kpps
# some nics like x540 supports only 2 queues, as number of cores will be
# used to create tx queues, restrict the cores to the trex parameter as per need
# 540 nics require this value to be set to 2
trex_core_count: 0

# When duration is '-1', the trex will run in continous burst mode
#  - name: pkt-64-10kpps
#    packet_size: 64
#    packet_rate: 10kpps
#    duration: 120
#    trex_profile_name: ''
#    trex_profile_path: ''
#    trex_profile_cm_name: ''
trex_test_config: []

testpmd_skip_resource: false
